"""Reconcile the committed generated data with cached BD/SP location tables.

Use this when the original workbook is not available locally. It preserves
editorial/special records already present and only adds or enriches wild
encounters from the canonical location pages.
"""
from __future__ import annotations

import json
from pathlib import Path

from encounter_reconciliation import upsert_canonical_encounter
from import_workbook import canonical_name, enrich_from_pokemondb


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "data" / "gameData.ts"


def main() -> None:
    text = OUTPUT.read_text(encoding="utf-8")
    start = text.index("export const gameData = ") + len("export const gameData = ")
    end = text.rfind(" as const;")
    data = json.loads(text[start:end])
    locations = {location["id"]: location for location in data["locations"]}
    pokemon_by_name = {canonical_name(item["name"]): item["id"] for item in data["pokemon"]}
    canonical = enrich_from_pokemondb(locations)
    additions = []

    for location in locations.values():
        for pokemon_name, details in canonical.get(location["id"], {}).items():
            pokemon_id = pokemon_by_name.get(pokemon_name)
            if pokemon_id is None or not details:
                continue
            _, added = upsert_canonical_encounter(
                location["encounters"],
                location_id=location["id"],
                pokemon_id=pokemon_id,
                canonical_details=details,
            )
            if added:
                additions.append({"location": location["name"], "pokemonId": pokemon_id})

    quality = data.setdefault("quality", {})
    quality["canonicalEncounterSource"] = "https://pokemondb.net/brilliant-diamond-shining-pearl"
    quality["canonicalEncounterSourcePolicy"] = "Generation 8 location tables are reconciled for wild encounters; workbook-only special encounters are preserved for manual review."
    quality["canonicalAdditions"] = additions
    data["locations"] = sorted(locations.values(), key=lambda item: (item["category"], item["name"]))
    OUTPUT.write_text("// Generated by scripts/import_workbook.py\nexport const gameData = " + json.dumps(data, ensure_ascii=False, indent=2) + " as const;\n", encoding="utf-8")
    print(f"Reconciled {len(additions)} missing location records from cached Pokémon Database tables")


if __name__ == "__main__":
    main()
